import { GoogleGenAI } from "@google/genai";
import { createUserContent, createPartFromUri } from "@google/genai";

async function summarizePDFwithGemini(){

    const result = await ai.models.generateContent({
        model: "gemini-2.5-flash-lite",
        contents: createUserContent([
        "\n\n",
        `give me downloadable anual report of tcs 2025`,
    ]),
});
console.log("✅ Summary generated by Gemini",result.text);
return result.text;
}

summarizePDFwithGemini();