import { GoogleGenAI, createUserContent, createPartFromUri } from "@google/genai";
import { Blob } from 'buffer';
import {GEMINI_API_KEY} from "../config/serverConfig.js"
const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

export async function summarizePDFwithGemini( buffer, mimeType) {
  try {
    
      const fileBlob = new Blob([buffer], { type: mimeType });
        console.log(`Uploading file of size ${buffer.length} bytes...`)
    const myfile = await ai.files.upload({
   file: fileBlob,
    config: {
      mimeType: mimeType,
    },
  config: { mimeType: "application/pdf" }, // required
  });
    console.log("✅ File uploaded to Gemini API");

    const result = await ai.models.generateContent({
      model: "gemini-2.5-flash-lite",
      contents: createUserContent([
        createPartFromUri(myfile.uri, myfile.mimeType),
        "\n\n",
        `You are an automated financial analyst. You will receive the raw text of an Annual Report of a publicly listed Indian company. Your task is to generate a neutral, factual, structured summary in Markdown.

The summary must follow the structure below, with each section treated as one page (max length ~12 pages). Use only the information from the report. If something is not available, write “Not Disclosed in Report.”

The tone must be neutral, simple, and explanatory — avoid promotional, judgmental, or advisory language.

 Business Snapshot & Model

Briefly describe the company’s core business in 1–2 sentences.

List its main products, services, and customer segments.

Revenue breakdown by business segment and geography (if disclosed).

Core revenue streams (product sales, services, contracts, subscriptions).

Key raw materials, suppliers, distribution channels, major cost drivers.

Any structural changes during the year (mergers, acquisitions, divestments).

 Industry & Macro Overview

Summarize industry environment and demand drivers.

Key challenges (e.g., raw material prices, regulation, competition).

Company’s relative positioning in the industry (only factual disclosures).

 Consolidated Financial Highlights 

Present a  table with columns as years and rows and the no. of years as given in the original report :

Revenue from Operations

EBITDA

Net Profit (Profit After Tax)

Basic EPS

EBITDA Margin %

Net Profit Margin %

ROE %

ROCE %

Debt-to-Equity Ratio

Trends Summary:
3–4 neutral sentences explaining main revenue/margin/debt drivers.

 Standalone Financial Highlights 

Use the same table format as Page 3, but for standalone results.

Trends Summary:
3–4 neutral sentences comparing standalone performance to consolidated.

Page 5 – Segment & Geography Performance

Create tables with:

Segment-wise: Revenue, EBIT/EBITDA, Margins %, % of total revenue.

Geography-wise: Revenue by region, % of total revenue.

 Shareholding Pattern

Promoter holding %

Institutional holding % (mutual funds, FIIs)

Retail & public holding %

Any major changes during the year.

 Capital Allocation, Dividend & Cash Flow

Capex during the year and planned capex (₹, if disclosed).

Dividend per share and payout ratio (last 3–5 years table if disclosed).

Equity actions (buybacks, issuances, allotments).

Debt levels (gross debt, net debt, debt/equity movement).

Cash flow summary: CFO, CFI, CFF (latest year).

Simple check: whether CFO > Net Profit or CFO < Net Profit.

Key Takeaways (bullets):

How cash was generated and deployed.

Any notable change in debt or equity.

 Governance & Management Snapshot

Total number of directors and number of independent directors.

Key leadership: Chairman, CEO/MD, CFO.

Key appointments or resignations.

Promoter shareholding and changes (if already not captured earlier).

Primary board committees (Audit, NRC, Risk, CSR).

 Auditor’s Report

Name of auditing firm.

Audit opinion (Unqualified, Qualified, Adverse, Disclaimer).

If Qualified/Modified, give factual reason.

Any Emphasis of Matter paragraphs (summarize factually).

 Risks & Other Material Disclosures

Risk Factors (categorized):

Business risks

Financial risks

Regulatory/legal risks

Other Disclosures:

Contingent liabilities (₹ value, nature).

Subsidiary/JV performance (if disclosed).

Regulatory filings or SEBI/BSE actions.

Share pledging (if any).

 ESG & CSR Highlights

CSR spend (₹ and % of average profits).

Focus areas (education, health, environment, etc.).

Environmental initiatives (renewable use, emissions reduction, etc.).

Governance/ethics disclosures (if mentioned).

Business Recap (5 points):

What does the company do?

Where does most of its revenue come from (by segment or geography)?

Where is the company spending or investing its money?

What are the key risks mentioned in the report?

What are the company’s stated plans for the future`
      ]),
    });
    console.log("✅ Summary generated by Gemini",result.text);
    return result.text;
  } catch (err) {
    console.error("❌ Gemini API Error:", err.message);
    throw new Error("Gemini summary generation failed");
  }
}
