import fs from "fs";
import puppeteer from "puppeteer";
import { markdownToHTML } from "../utilities/markdownUtil.js";

/**
 * Convert Markdown text into PDF buffer with header, footer, and watermark
 */
export async function markdownToPDFBuffer(markdownText) {
  try {
  // Load logos
  const logoBase64 = fs.readFileSync("logo.svg", "base64");
  const logoFooter = fs.readFileSync("footer-logo.svg", "base64");

  // Convert Markdown → HTML
  const htmlContent = markdownToHTML(markdownText);

  // Full HTML template (with last page)
  const html = `
<html>
  <head>
    <title>Summary Report</title>
    <style>
      body { 
        font-family: 'Segoe UI', Arial, sans-serif; 
        padding: 40px; 
        line-height: 1.6;
        color: #222;
      }

      h1, h2, h3 {
        color: #333;
      }

      table { 
        width: 100%; 
        border-collapse: collapse; 
        margin-top: 20px; 
      }

      th, td { 
        border: 1px solid #ddd; 
        padding: 8px; 
        text-align: left; 
      }

      th { 
        background-color: #f2f2f2; 
      }

      .header {
        text-align: left;
        border-bottom: 2px solid #ddd;
        padding-bottom: 10px;
        margin-bottom: 40px;
      }

      .header img {
        width: 180px;
        height: auto;
      }

      /* Watermark */
      body::before {
        content: "Tickernote";
        position: fixed;
        top: 45%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(-30deg);
        font-size: 72px;
        color: rgba(150, 150, 150, 0.08);
        z-index: -1;
        white-space: nowrap;
        pointer-events: none;
      }

      /* Last Page */
      .page-break {
  page-break-before: always;
  margin: 0;
  padding: 0;
}

.last-page {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: justify;
  background: linear-gradient(135deg, #f8f9fb, #f2f4f7);
  color: #333;
  padding: 60px 80px;
  box-sizing: border-box;
  min-height: 100vh;
  page-break-after: avoid;
}

      .last-page img {
        width: 140px;
        margin-bottom: 20px;
      }

      .last-page h1 {
        font-size: 26px;
        margin-bottom: 10px;
      }

      .last-page p {
        font-size: 15px;
        max-width: 600px;
        color: #555;
        margin: 8px auto;
      }

      .last-page .footer {
        margin-top: 40px;
        font-size: 13px;
        color: #777;
      }

    </style>
  </head>

  <body>
    <!-- Header -->
    <div class="header">
      <img src="data:image/svg+xml;base64,${logoBase64}" alt="Logo" />
    </div>

    <!-- Main Content -->
    <div class="content">
      ${htmlContent}
    </div>


<!-- Epilogue / Last Page -->
<div class="last-page" style="
  width: 100%;
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;
  text-align: justify;
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
  color: #333;
  padding: 40px 60px;
  box-sizing: border-box;
  overflow: hidden;
  page-break-before: always;
">

  <img 
    src="data:image/svg+xml;base64,${logoBase64}" 
    alt="Tickernote Logo" 
    style="width: 120px; height: auto; margin-bottom: 20px;"
  />

  <h1 style="
    font-size: 18px;
    font-weight: 600;
    color: #111;
    text-transform: uppercase;
    letter-spacing: 0.4px;
    margin-bottom: 15px;
  ">
    Disclaimer
  </h1>

  <div style="flex: 1; max-width: 720px; font-size: 11px; line-height: 1.6; color: #444; overflow: hidden;">
    <p style="margin-bottom: 10px;">
      This summary has been automatically generated by <strong>Tickernote</strong> using publicly available company reports, 
      including but not limited to Annual Reports, DRHPs, and regulatory filings. It is intended solely for educational 
      and informational purposes to help readers understand business and financial information in a simplified manner.
    </p>

    <p style="margin-bottom: 10px;">
      This document does not constitute investment advice, research report, or recommendation of any kind, 
      whether under SEBI (Research Analysts) Regulations, 2014 or otherwise. Tickernote and its creators do not 
      provide investment, legal, or financial advice and are not registered with SEBI as research analysts or advisers.
    </p>

    <p style="margin-bottom: 10px;">
      Users should not make investment or trading decisions based on this content and are advised to consult 
      qualified financial professionals before acting on any information. While reasonable care is taken to ensure 
      accuracy, Tickernote makes no warranty as to the completeness or reliability of this summary.
    </p>

    <p style="margin-bottom: 0;">
      © Tickernote — AI-generated educational summary. All information remains the property of the original company 
      and its respective sources.
    </p>
  </div>

  <div style="
    width: 100%;
    text-align: center;
    font-size: 9px;
    color: #666;
    border-top: 1px solid #ddd;
    padding-top: 8px;
    margin-top: 20px;
  ">
    &copy; ${new Date().getFullYear()} Tickernote — All rights reserved.
  </div>
</div>


  </body>
</html>`;

  // Puppeteer → PDF
  const browser = await puppeteer.launch({
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
    headless: true,
  });

  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: "domcontentloaded" });

  const pdfBuffer = await page.pdf({
    format: "A4",
    printBackground: true,
   margin: { top: "40px", bottom: "60px", left: "40px", right: "40px" },
    displayHeaderFooter: true,
    headerTemplate: `<div></div>`,
    footerTemplate: `
      <div style="
  width: 100%;
  font-size: 10px;
  padding: 8px 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-top: 1px solid #ddd;
  box-sizing: border-box;
">
  <div style="flex: 1; text-align: left; white-space: nowrap;">
    Page <span class='pageNumber'></span> of <span class='totalPages'></span>
  </div>

  <div style="
    flex: 2;
    text-align: center;
    line-height: 1.4;
    padding: 0 10px;
    font-size: 12px;
    color: #555;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  ">
    AI summary by <strong>Tickernote</strong> — not investment advice.
  </div>

  <div style="flex: 1; text-align: right;">
    <img 
      src="data:image/svg+xml;base64,${logoFooter}" 
      alt="Tickernote Logo" 
      style="width: 70px; height: auto; vertical-align: middle;"
    />
  </div>
</div>
`
  });

  await browser.close();
  console.log("✅ PDF generated with final epilogue page");
  return pdfBuffer;

}catch (err) {
    console.error("❌ PDF generation Error:", err.message);
    throw new Error("PDF generation failed");
  }
}
